-- SPARTAN 💎 LUCKY WHEEL — Supabase schema
create table if not exists public.spins (
  id bigint generated by default as identity primary key,
  display_name text not null check (char_length(display_name) between 1 and 40),
  number integer not null unique check (number between 2 and 10),
  participant_key text not null unique,
  created_at timestamptz not null default now()
);

-- Public reading is needed so everyone sees the same history.
alter table public.spins enable row level security;

drop policy if exists "Anyone can read spins" on public.spins;
create policy "Anyone can read spins"
on public.spins for select
to anon, authenticated
using (true);

-- Atomic spin: picks one unused number and records it in one transaction.
create or replace function public.spin_wheel(p_name text)
returns table(number integer, display_name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  chosen integer;
  pkey text;
begin
  p_name := btrim(p_name);
  if p_name is null or char_length(p_name) < 1 or char_length(p_name) > 40 then
    raise exception 'Invalid name';
  end if;

  -- Browser-generated participant key is supplied by this function via a stable
  -- fingerprint stored by the page would be preferable. For a simple public game,
  -- the display name is treated as the participant identity.
  pkey := lower(p_name);

  if exists(select 1 from spins where participant_key=pkey) then
    raise exception 'already used';
  end if;

  select n into chosen
  from generate_series(2,10) n
  where not exists(select 1 from spins s where s.number=n)
  order by random()
  limit 1;

  if chosen is null then raise exception 'No numbers left'; end if;

  insert into spins(display_name,number,participant_key)
  values(p_name,chosen,pkey);

  return query select chosen,p_name;
end;
$$;

revoke all on function public.spin_wheel(text) from public;
grant execute on function public.spin_wheel(text) to anon, authenticated;

-- SPARTAN 💎 is fixed at #1 and is intentionally not stored in spins,
-- because the public history can display it in the website header if desired.
